language: en
pipeline: supervised_embeddings
policies:
- name: EmbeddingPolicy
  max_history: 5
  batch_size: 50
  epochs: 200
  max_training_samples: 300
- name: FallbackPolicy
- name: MemoizationPolicy
- name: FormPolicy
- name: MappingPolicy
